### ISSUE TITLE
Omnitool Map

### ISSUE THREAD

**Issue by GermanLetsKotz** [Berserker66/omnitool#28]
My Map "GLK" doesn´t load until the end, it stops at the half.And whenever I want to display another world it has an error. What should I do?

**Comment by Berserker66** [comment]
Just to make sure it usually works, I just booted up Terraria, made a new world and loaded it and it worked fine.

Some things then:
Can you send a screenshot of the problem, as well as a copy of the world file? They are in My Documents\My Games\Terraria\Worlds

I should also point that that this is a common error if you pirated an older version of Terraria, but could just as well be caused by mods, so - any of those present?

Also Operating System and Terraria version would help, this program does run on mac, linux and windows, so I mean, I can guess you're likely using windows, but it's not guaranteed.

**Comment by GermanLetsKotz** [comment]
Well, I didn't pirate Terraria, I bought it from a store.

**Comment by GermanLetsKotz** [comment]
PS Ich habe keine Mods und wenn ich in meinen Dokumenten auf meine Welt gehe, geht sie nicht auf. Egal ^^ Omnitool hat mir aber das, was ich brauchte gegeben, den Standpunkt vom Dschungeltempel, zum Glück war er auf der linken Seite.
